accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),

]

blog/urls.py
from django.urls import path
from .views import (
    HomeView,
    PostNewView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
)

app_name = 'blog'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('post/new', PostNewView.as_view(), name='post_new'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('post/update/<int:pk>', PostUpdateView.as_view(), name='update'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name="delete"),
]

site_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settingsx


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)
    photo = models.ImageField()
    about = models.CharField(max_length=255, default='null')

blog/models.py
from django.db import models
from jalali_date import date2jalali
from django.urls import reverse
from django.utils import timezone
from datetime import date



class Blog(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField()
    body = models.TextField()
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    date = models.DateField(default=date.today)
    photo = models.ImageField()

    def __str__(self):
        return self.title

    def get_jalali_date(self):
        return date2jalali(self.date)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    body = models.TextField(null=False, blank=False)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.body
# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + \
            ('email', 'age', 'about', 'photo')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

blog/forms.py
from django import forms
from .models import Blog, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'excerpt', 'body', 'author', 'date', 'photo']



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

accounts/views.py
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, CreateView, DetailView, FormView
from django.views.generic.edit import UpdateView, DeleteView
from .models import Blog
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from django.views.generic.detail import SingleObjectMixin

def all_blogs(request):
    blog_count = Blog.objects.count()
    blogs = Blog.objects.all()
    return render(request, 'blog/all_blogs.html', {'blogs': blogs, 'blog_count': blog_count})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

class HomeView(View):
    #model = Blog
    template_name = 'home.html'
    paginate_by = 1

    def get(self, request):
        posts = Blog.objects.all()
        paginator = Paginator(posts, self.paginate_by)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'post_list': page_obj
        }

        return render(request, self.template_name, context)


class CommentGet(DetailView):
    model = Blog
    template_name = 'post_single.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):
    model = Blog
    form_class = CommentForm
    template_name = "post_single.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        post = self.get_object()
        return reverse("post_detail", kwargs={'pk': post.pk})

class PostDetailView(View):

    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class PostNewView(CreateView):
    model = Blog
    template_name = 'post_new.html'
    form_class = PostForm
    success_url = reverse_lazy('home')
    # fields = ['title', 'excerpt', 'body', 'author', 'date', 'photo']


class PostUpdateView(UpdateView):
    model = Blog
    template_name = 'post_update.html'
    fields = ['title', 'excerpt', 'body', 'photo']


class PostDeleteView(DeleteView):
    model = Blog
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

# Create your views here.

blog/templates/blog/all_blogs.html
{% extends 'base.html' %}
{% load static %}
{% load jformat %}
{% load jalali_tags %}

{% block header_reference %}
    <link rel="stylesheet" href="{% static 'home/menu.css' %}">
    <link rel="stylesheet" href="{% static 'font.css' %}">
{% endblock %}

{% block content %}
    &nbsp;
    <h2 class="text-post"> تعداد پست ها در این صفحه {{ blog_count }} است </h2>
    &nbsp;

    <div class="text-all-post">
        {% for blog in blogs %}
            <a href="{% url 'blog:detail' blog_id=blog.id %}"><h1>{{ blog.title }}</h1></a>
            &nbsp;
            <h3>{{ blog.get_jalali_date|jformat:"%A %d %B   %Y "}}</h3>
            &nbsp;
            <p>{{ blog.description|striptags|truncatechars:100 }}</p>
            &nbsp;
        {% endfor %}
        &nbsp;
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block header_reference %}
    <link rel="stylesheet" href="{% static 'home/menu.css' %}">
{% endblock %}


{% block content %}
	{{ blog.title }}
    {{ blog.description }}
    {{ blog.date }}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Moderna Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
    <link rel="stylesheet" href="{% static 'Fonts/font.css' %}">
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna
  * Updated: May 30 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="text-light"><a href="#"><span>Moderna</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>          
          <li><a href="{% url 'blog:home' %}">Home</a></li>          
          {% if user.is_authenticated %}
            <li><a href="#">+Add new post</a></li>
            <li class="dropdown"><a href="#">{{ user.username }} <span><i class="bi bi-chevron-down"></i></span></a>
              <ul>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'password_change' %}">Password Change</a></li>
                <li><a href="{% url 'password_reset' %}">Password Reset</a></li>
              </ul>
            </li>
          {% else %}
            <li class="dropdown"><a href="#">User <span><i class="bi bi-chevron-down"></i></span></a>
              <ul>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">Sign Up</a></li>
              </ul>
            </li>            
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    {% block content %}    
    {% endblock content %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>About Moderna</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
     <!-- ======= Blog Section ======= -->
     <section class="breadcrumbs">
        <div class="container">
  
          <div class="d-flex justify-content-between align-items-center">
            <h2>Home</h2>
  
            <ol>
              <li><a href="{% url 'blog:home' %}">Home</a></li>              
            </ol>
          </div>
  
        </div>
      </section><!-- End Blog Section -->
  
      <!-- ======= Blog Section ======= -->
      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
  
          <div class="row">
  
            <div class="col-lg-8 entries">
              {% if post_list %}
                {% for post in post_list %}
                  <article class="entry">
      
                    <div class="entry-img">
                      <img src="{{ post.photo.url }}" alt="" class="img-fluid">
                    </div>
      
                    <h2 class="entry-title">
                      <a href="{% url 'post_detail' post.pk  %}">{{ post.title }}</a>
                    </h2>
      
                    <div class="entry-meta">
                      <ul>
                        <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ post.author }}</a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ post.date }}</time></a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">12 Comments</a></li>
                      </ul>
                    </div>
      
                    <div class="entry-content">
                      <p>
                        {{ post.excerpt }}
                      </p>
                      <div class="read-more">
                        <a href="{% url 'post_detail' post.pk  %}">Read More</a>
                      </div>
                    </div>
      
                  </article><!-- End blog entry -->            
                {% endfor %}

                {% if post_list.has_other_pages %}
                  <div class="blog-pagination">
                    <ul class="justify-content-center">                    
                      
                      {% if post_list.has_previous %}
                        <li class="page-item">
                          <a href="?page={{ post_list.previous_page_number }}">&laquo</a>
                        </li>
                      {% else %}
                        <li class="page-item disabled">
                          <a class="page-link">&laquo</a>
                        </li>
                      {% endif %}

                      {% for i in post_list.paginator.page_range %}
                        {% if post_list.number == i %}
                          <li class="page_item active">
                            <a class="page-link">{{ i }}</a>
                          </li>
                        {% else %}
                          <li class="page-item">
                            <a href="?page={{i}}" class="page-link">{{ i }}</a>
                          </li>
                        {% endif %}
                      {% endfor %}                      

                      {% if post_list.has_next %}
                        <li class="page-item">
                          <a href="?page={{ post_list.next_page_number }}">&raquo</a>
                        </li>
                      {% else %}
                        <li class="page-item disabled">
                          <a class="page-link">&raquo</a>
                        </li>
                      {% endif %}

                    </ul>
                  </div>
                {% endif %}

              {% else %}
                <h2>No post is available!</h2>
              {% endif %}
            </div><!-- End blog entries list -->
  
            <div class="col-lg-4">
  
              {% block sidebar %}
                {% include 'sidebar.html' %}
              {% endblock sidebar %}
  
            </div><!-- End blog sidebar -->
  
          </div>
  
        </div>
      </section><!-- End Blog Section -->

{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
  
          <div class="d-flex justify-content-between align-items-center">
            <h2>Blog</h2>
  
            <ol>
              <li><a href="{% url 'home' %}">Home</a></li>
              <li>Delete post</li>
            </ol>
          </div>
  
        </div>
      </section><!-- End Blog Section -->
  
      <!-- ======= Blog Single Section ======= -->
      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
  
          <div class="row">
  
            <div class="col-lg-8 entries">
  
              <form method="post">
                {% csrf_token %}                
                <p>Are you sure you want to delete <strong>"{{ post.title }}"</strong>?</p>
                <button type="submit" class="btn btn-success">Yes</button>
              </form>
  
            </div><!-- End blog entries list -->            
  
          </div>
  
        </div>
      </section><!-- End Blog Single Section -->

{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <section class="breadcrumbs">
        <div class="container">

        <div class="d-flex justify-content-between align-items-center">
            <h2>New Blog Post</h2>

            <ol>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li>New Blog Post</li>              
            </ol>
        </div>

        </div>
    </section>

    <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
            <div class="row">
                <div class="col-lg-12 netries">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <br>
                        <input type="submit" value="Publish" class="btn btn-success">
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/post_single.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
  
          <div class="d-flex justify-content-between align-items-center">
            <h2>Blog</h2>
  
            <ol>
              <li><a href="{% url 'home' %}">Home</a></li>
              <li>{{ post.title }}</li>
            </ol>
          </div>
  
        </div>
      </section><!-- End Blog Section -->
  
      <!-- ======= Blog Single Section ======= -->
      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
  
          <div class="row">
  
            <div class="col-lg-8 entries">
  
              <article class="entry entry-single">
  
                <div class="entry-img">
                  <img src="{{ post.photo.url }}" alt="" class="img-fluid">
                </div>
  
                <h2 class="entry-title">
                  <a href="blog-single.html">{{ post.title }}</a>
                </h2>
  
                <div class="entry-meta">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ post.author }}</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ post.date }}</time></a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">12 Comments</a></li>
                  </ul>
                </div>
  
                <div class="entry-content">
                  <p>{{ post.body }}</p>
                </div>
  
                {% if user.username == post.author.username %}
                    <div class="entry-footer">                  
                    <ul class="cats">
                        <i class="bi bi-pen-fill"></i>
                        <li><a href="{% url 'update' post.pk %}">Update</a></li>
                        <i class="bi bi-file-x"></i>
                        <li><a href="{% url 'delete' post.pk %}">Delete</a></li>
                    </ul>                                    
                    </div>
                {% endif %}
  
              </article><!-- End blog entry -->
  
              <div class="blog-author d-flex align-items-center">
                <img src="{{ post.author.photo.url }}" class="rounded-circle float-left" alt="">
                <div>
                  <h4>Jane Smith</h4>
                  <div class="social-links">
                    <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                    <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                    <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                  </div>
                  <p>{{ post.author.about }}</p>
                </div>
              </div><!-- End blog author bio -->
  
              <div class="blog-comments">

                {% if post.comment_set.count > 1 %}
                  <h4 class="comments-count">{{ post.comment_set.count }} Comments</h4>
                {% else %}
                  <h4 class="comments-count">{{ post.comment_set.count }} Comment</h4>
                {% endif %}
  
                {% for comment in post.comment_set.all %}
                  <div id="comment-1" class="comment">
                    <div class="d-flex">
                      <div class="comment-img"><img src="{{ comment.author.photo.url }}" alt=""></div>
                      <div>
                        <h5>{{ comment.author }}</h5>
                        <time datetime="2020-01-01">{{ comment.date }}</time>
                        <p>{{ comment.body }}</p>
                      </div>
                    </div>
                  </div><!-- End comment #1 -->                                 
                {% endfor %}

                {% if user.is_authenticated %}
                  <div class="reply-form">
                    <h4>{{ user.username }} Leave a Reply</h4>
                    <p>Your email address will not be published. Required fields are marked * </p>
                    <form method="post">
                      {% csrf_token %}
                      {{ form | crispy }}                      
                      <button type="submit" class="btn btn-primary">Post Comment</button>    
                    </form>
    
                  </div>
                {% endif %}
  
              </div><!-- End blog comments -->
  
            </div><!-- End blog entries list -->
  
            <div class="col-lg-4">
  
                {% block sidebar %}
                    {% include 'sidebar.html' %}
                {% endblock sidebar %}
  
            </div><!-- End blog sidebar -->
  
          </div>
  
        </div>
      </section><!-- End Blog Single Section -->

{% endblock content %}

templates/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
  
          <div class="d-flex justify-content-between align-items-center">
            <h2>Blog</h2>
  
            <ol>
              <li><a href="{% url 'home' %}">Home</a></li>
              <li>Update post</li>
            </ol>
          </div>
  
        </div>
      </section><!-- End Blog Section -->
  
      <!-- ======= Blog Single Section ======= -->
      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
  
          <div class="row">
  
            <div class="col-lg-8 entries">
  
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <br>
                <button type="submit" class="btn btn-success">Update post</button>
              </form>
  
            </div><!-- End blog entries list -->            
  
          </div>
  
        </div>
      </section><!-- End Blog Single Section -->

{% endblock content %}